### ISSUE TITLE
Cannot get the series info when value type of tag 00200010 is missing

### ISSUE THREAD

**Issue by dinhnam2901** [knopkem/dicomweb-proxy#10]
Hi @knopkem!
When I using dicomweb proxy to get the series info. If the  value type of tag 00200010 of image is missing. The dicomweb proxy will be time out and don't response any data. I expected it to response data as normal. 
What should I do to get it ?
Thank you so much !

**Comment by knopkem** [comment]
It might be related to the PACS that you query against, as this should normally work (and it does for me). I suggest that you test first with the underlying c-find service using this plugin (which is used in dicomweb-proxy): https://github.com/knopkem/dicom-dimse-native. See the example folder for how to do this. If this works for you than we can check the dicomweb-proxy.

**Comment by dinhnam2901** [comment]
Thank for your answer!
I have been test first with the underlying c-find service using this plugin as you suggetted. And, it work correctly.

**Comment by knopkem** [comment]
ok, can you set verboseLogging to true and post the result, please?

**Comment by dinhnam2901** [comment]
Dear @knopkem!
I have been set verboseLogging to true and run get the series info by dicom proxy.
The dicomweb proxy will be time out and don't response any data as I mentioned at the beginning.
I have been copy all logging in file attachment: 
[error_get_siries_with_dicomproxy_log.txt](https://github.com/knopkem/dicomweb-proxy/files/5215878/error_get_siries_with_dicomproxy_log.txt)
Can you check it and give me the solution ?
Thank you so much!

**Comment by knopkem** [comment]
ok, I just checked the code and the only reason why it might be hanging is in the case the c-find responds with an error code, which wasn't properly handled. So please pull the latest version from master and try again. This time there might be a better error logged that gives more insight about the issue. Cheers

**Comment by dinhnam2901** [comment]
I undestood. I will trying it.
Thank you for your support!

**Comment by dinhnam2901** [comment]
Dear @knopkem!

I have been pull the lastest version from master as your mentioned above.
Then, I run get the series info by dicom proxy. 
The dicomweb proxy will be still time out and don't response any data as I mentioned at the beginning.
I have been copy all logging in file attachment:
[error_get_series_with_dicomproxy_log_1.txt](https://github.com/knopkem/dicomweb-proxy/files/5217196/error_get_series_with_dicomproxy_log_1.txt)

I trying create a condition in file utils.js as: 
![image](https://user-images.githubusercontent.com/20145650/93064424-b54b4d00-f6a1-11ea-99b2-1fe984e43f36.png)
Then, I run get the series info by dicom proxy again. 
The dicomweb proxy will be not time out and return the empty array. 
I have been copy all logging in file attachment:
[error_get_series_with_dicomproxy_log_2.txt](https://github.com/knopkem/dicomweb-proxy/files/5217225/error_get_series_with_dicomproxy_log_2.txt)

Once again, can you help me check it ?
Thank you so much!

**Comment by knopkem** [comment]
You are right, I overlooked this else case and it now points to the problem. The issue was to be found in dicom-dimse-native failing to convert to json in case of empty results (to be honest, this plugin isn't tested that much).
Anyway, I've updated both projects, so make sure to update your dependencies before trying. The response for attributes that have empty values should now be an empty array (this might not totally be dicomweb compliant, I think the whole attribute should then be omitted, let me know if this is a problem).

**Comment by dinhnam2901** [comment]
> Anyway, I've updated both projects
But, I find and see that you update for dicom-dimse-native only, the dicomweb-proxy haven't update at this time.
I will import new dicom-dimse-native into dicomweb-proxy or wait for you update both ?

**Comment by knopkem** [comment]
Forgot to push, sorry. Was waiting for the prebuild to finish and then forgot about it ^^

**Comment by dinhnam2901** [comment]
I see the update for both project at the moment.
I will trying it.
Thank you so much!

**Comment by dinhnam2901** [comment]
Dear @knopkem!
When I download the newest source of dicomweb proxy at version 1.0.9
Then I run the command: "npm install" to install it, I will get an error as bellow:
```
$ npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for dicom-dimse-native@1.0.9.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'dicomweb-proxy-20200915'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\namnd\AppData\Roaming\npm-cache\_logs\2020-09-15T03_18_26_131Z-debug.log
```
I wonder why, something are incorrect ? Or I run a incorrect command ?

**Comment by knopkem** [comment]
weird, maybe there was something wrong with the upload of the new prebuild, will check later. thanks

**Comment by knopkem** [comment]
what's the os and node version you are using?

**Comment by dinhnam2901** [comment]
I using window8.1 and node 12.18.0

**Comment by knopkem** [comment]
Ok, something must have gone wrong when publishing the update to npm. It should work now. Let me know how it goes.

**Comment by dinhnam2901** [comment]
At now, I can update to version 1.0.9 successful.
Thank you so much!

**Comment by dinhnam2901** [comment]
And, by using new version of your project at 1.0.9. My problem has been solved.
Thank you for your support!
