### ISSUE TITLE
Uncaught (in promise) Error: decodeRGB

### ISSUE THREAD

**Issue by wx0322** [knopkem/dicomweb-proxy#108]
hi,
   I need some help.

**ohif-viewer**:  v3-stable

**app-config.js**:
![image](https://user-images.githubusercontent.com/37427445/211710152-d49beb3c-ba95-4a6c-a8bc-678f476badb7.png)

**result screen**:
![image](https://user-images.githubusercontent.com/37427445/211710355-ae12bb78-5b2d-4f10-8a0b-51e439c03ba7.png)

**web console error info**:
`Uncaught (in promise) Error: decodeRGB: rgbBuffer length must be divisible by 3
    at t (cornerstoneWADOImageLoader.min.js:1:61233)
    at Ee (cornerstoneWADOImageLoader.min.js:1:79329)
    at Ce (cornerstoneWADOImageLoader.min.js:1:79406)
    at cornerstoneWADOImageLoader.min.js:1:84055`

**ps:** when i modify the app-config.js to wadouri, everything is ok.

How could I fix this?  I want to use wado-rs.
thanks.

**Comment by knopkem** [comment]
Hi, you wrote wadours but it should be wadors. Can you try again?

**Comment by wx0322** [comment]
It works now.
Thank you very much for your help！
