### ISSUE TITLE
Upgrade OHIF Viewer

### ISSUE THREAD

**Issue by fadjar340** [knopkem/dicomweb-proxy#109]
Is it any documentation to upgrade the OHIF Viewer to version 4.12.49?

Regards,
Fadjar340

**Comment by knopkem** [comment]
Yes, see the pinned issue: https://github.com/knopkem/dicomweb-proxy/issues/41

**Comment by fadjar340** [comment]
Thanks...
I'll try to build this..

**Comment by fadjar340** [comment]
Hi...

The newest version of the OHIF Viewer succeeded to built and also the docker image for dicomweb-proxy, but still in private repo.
If you need the Dockerfile, I'm happy to share...


Regards,
Fadjar340

**Comment by pablosbravo** [comment]
Hello @fadjar340 ! In theory, from what I saw regarding OHIF, the latest version integrates the dicomweb proxy to support PACS that don't work with WADO. Do you have an example of the 'app-config.js' configuration or a docker-compose file? I would greatly appreciate it.
