### ISSUE TITLE
DIMSE result limitation

### ISSUE THREAD

**Issue by fadjar340** [knopkem/dicomweb-proxy#110]
Hi...

Is it possible that in the C-FIND have limitation of the result from the DIMSE server?
Since I have more than 190k data, it's takes time and the viewer send error message on the studies query, even the query have limit.

Below my result data and this made problem in the viewer page.

```
D: DcmDataset::read() TransferSyntax="Little Endian Implicit"
--
D: DcmDataset::read() TransferSyntax="Little Endian Implicit"
I: Received Find Response 91644
D: ===================== INCOMING DIMSE MESSAGE ====================
D: Message Type : C-FIND RSP
D: Message ID Being Responded To : 1
D: Affected SOP Class UID : FINDStudyRootQueryRetrieveInformationModel
D: Data Set : present
D: DIMSE Status : 0xff01: Pending: Warning - Unsupported optional keys
D: ======================= END DIMSE MESSAGE =======================


```

With the limit, I think the result from the query URL will response faster. I think my request will make major changes, because you need to store the last number of the result, and perhaps it's not supported by DIMSE protocol..:)

Perhaps you can give enlightenment about this... :))

Regards,
Fadjar340

EDIT:
from https://support.dcmtk.org/docs/findscu.html
There is limit option C-FIND response, instead the default is unlimited, using
```
  -Xlo  --limit-output  [n]umber: integer
          limit number of responses extracted to file to n
          (default: unlimited)
```

**Comment by fadjar340** [comment]
Hi,

I can manage this with modify the OHIF-Viewer code to get what I want and now working smooth the server in Kubernetes


Regards,
Fadjar340

**Comment by wx0322** [comment]
> Hi...
> 
> Is it possible that in the C-FIND have limitation of the result from the DIMSE server? Since I have more than 190k data, it's takes time and the viewer send error message on the studies query, even the query have limit.
> 
> Below my result data and this made problem in the viewer page.
> 
> ```
> D: DcmDataset::read() TransferSyntax="Little Endian Implicit"
> --
> D: DcmDataset::read() TransferSyntax="Little Endian Implicit"
> I: Received Find Response 91644
> D: ===================== INCOMING DIMSE MESSAGE ====================
> D: Message Type : C-FIND RSP
> D: Message ID Being Responded To : 1
> D: Affected SOP Class UID : FINDStudyRootQueryRetrieveInformationModel
> D: Data Set : present
> D: DIMSE Status : 0xff01: Pending: Warning - Unsupported optional keys
> D: ======================= END DIMSE MESSAGE =======================
> ```
> 
> With the limit, I think the result from the query URL will response faster. I think my request will make major changes, because you need to store the last number of the result, and perhaps it's not supported by DIMSE protocol..:)
> 
> Perhaps you can give enlightenment about this... :))
> 
> Regards, Fadjar340
> 
> EDIT: from https://support.dcmtk.org/docs/findscu.html There is limit option C-FIND response, instead the default is unlimited, using
> 
> ```
>   -Xlo  --limit-output  [n]umber: integer
>           limit number of responses extracted to file to n
>           (default: unlimited)
> ```

Can you tell me how to operate it? I have the same problem.
