### ISSUE TITLE
Distorted US image

### ISSUE THREAD

**Issue by GProg2** [knopkem/dicomweb-proxy#112]
When I view an ultrasound image the image is distorted. type (RGB)

**Comment by GProg2** [comment]
![anom](https://user-images.githubusercontent.com/122978513/213155836-21526c9d-dd33-44a3-9439-e103dd5d51b8.png)

**Comment by knopkem** [comment]
Hi, this seems like a bug in the [OHIF viewer.](https://github.com/OHIF/Viewers) 
This project is only about proxying the requests between PACS and the Viewer and just bundles the viewer for ease of use. If you can sucessfully view this image with e.g. orthanc or dcm4chee and OHIF than please come back with it and upload an anonymized sample file.

**Comment by GProg2** [comment]
Thank you,
I tried as you told me with OHIF via ORTHANC.
View the image correctly.
I send you a test US.
The name entered is not real.

[dicom_US.zip](https://github.com/knopkem/dicomweb-proxy/files/10464833/dicom_US.zip)

**Comment by knopkem** [comment]
ok, will have a look

**Comment by knopkem** [comment]
Hi, can you check the uploaded files. When testing with various viewers including OHIF with proxy they all look like below.

![image](https://user-images.githubusercontent.com/994526/213875910-b2d1ad4a-ceb4-4244-921c-6d76314b3de9.png)

**Comment by GProg2** [comment]
Thanks for your availability, but unfortunately by loading the same image with the ohif integrated in dicomweb-proxy I always keep having the same problem, I wonder at this point if it could depend on some different library between mine and your version.
Can you give me some advice on how to reinstall and which versions did you use?

**Comment by knopkem** [comment]
Hi,
I did notice the same error when first trying your images and could also only load it when changing TS. The error comes from the underlying dcmtk toolkit (not my work). I did have a look at the image properties and for me the RGB value seems to be correct, however I could not find any tool that was rendering the images in color, so I guess there is an underlying problem with those images.
I used the latest version of this project (1.7.2) which comes with OHIV viewer 4.12.25
Upgrading depends how you got the code (either via npm, or git or file copy), so basically you just need to update the code to the latest from the main branch 'git fetch && git pull' (see 1 and 2) if you get a problem here) and perform 'npm install' again. Just make sure not to override your default.js. There is 2 ways to do this:
1) (preferred) Don't change default.js, but rather create a file called development.js (or production.js) and copy the content of your modified default.js. Those files are automatically overriding anything over default.js but are not part of the checked in source (so won't change if you update the repository).
2) Just stash your changes, update the branch and reapply them again:
* git stash
* git fetch && git pull
* git stash apply

Good luck

**Comment by knopkem** [comment]
I just released a new version 1.8.0 that comes with the latest OHIF viewer (v12.4.50).

**Comment by GProg2** [comment]
thanks, I try it.

**Comment by GProg2** [comment]
with 1.7.2 it works perfectly

with the version I had 1.6.4 and 1.8.0 it doesn't work.

**Comment by Shuun26** [comment]
Hi! I'm having the same error, for some reason RGB images don't load properly, in this case it's an "CT" study.

![image](https://github.com/knopkem/dicomweb-proxy/assets/68860132/6f0a735f-9668-40e9-b671-fdff7eec8393)

Note: I prove it with 1.7.2, 1.8.0 and finally 1.8.1

**Comment by knopkem** [comment]
Thanks for the info, will update the code.
