### ISSUE TITLE
Explicit return on routes

### ISSUE THREAD

**Issue by dorronso** [knopkem/dicomweb-proxy#114]
Awesome job. Whilst tweaking the project to suit my personal requirements I have come across this:
(https://www.fastify.io/docs/latest/Reference/Routes/#async-await):
> In this case do not forget to return reply or await reply in your async handler or you will introduce a race condition in certain situations.

Although I have not experienced race conditions, I was wondering if it would be necessary to return reply on ohif routes.
(https://github.com/knopkem/dicomweb-proxy/blob/e3ef28aff1a81139c9dcbd79c6825dde2b4c7df2/src/routes/routes.ts)

**Comment by knopkem** [comment]
Thanks for the hint. Will have a look and adapt. Cheers

**Comment by knopkem** [comment]
done
