### ISSUE TITLE
Search for patients

### ISSUE THREAD

**Issue by ruben-cruz** [knopkem/dicomweb-proxy#116]
Does anyone know how we can search for patients only, for example, "/rs/patients"? dicomweb-proxy has this route or we have to create it? If so, does anyone have any suggestion on how this can be done?

Thanks.

**Comment by knopkem** [comment]
While it would be possible to add such a route to the proxy, it is not part of the dicomweb definition. Qido-rs is meant to reflect c-find using the so called "Study Root Model" (and not the patient root model" thus there is not patient level defined. However you can still use the study routes to query for studies of patients using only patient attributes (name, Id, etc.) and then simply merge those duplicate together.

**Comment by ruben-cruz** [comment]
@knopkem ok thanks.

I have another doubt regarding the wadouri route... I'm calling the WADOURI service like this: `http://localhost:5000/wadouri?studyUID=XXXX&seriesUID=XXXX&objectUID=XXXX&contentType=image/jpeg` but it returns 500 and the following appears on the log file (also nothing is written on the ./data file):

```
23:10:01.802 INFO  fetch start: 
23:10:01.805 INFO  fetch finished: 
23:10:01.806 ERROR recompression failure Invalid source path set, no DICOM files found 
23:10:01.807 ERROR  
23:10:01.807 ERROR failed to compress 
```

Is something that I'm doing wrong on the WADOURI call parameter?
