### ISSUE TITLE
wadoRs buffer problem

### ISSUE THREAD

**Issue by ruben-cruz** [knopkem/dicomweb-proxy#118]
Hi, I'm using the WadoRS route - `/rs/studies/:studyInstanceUid/series/:seriesInstanceUid/instances/:sopInstanceUid/frames/:frame` and I've noticed that the type inside the contenType constant is `application/octed-stream` instead of `application/octet-stream`. I have changed that, but I continue to have problems showing the image returned by the buffer... I don't know if is missing some additional configuration. Can anyone help me? My code is like this:

```
try {
    const data = await fs.promises.readFile(pathname);
    const dataset = dicomParser.parseDicom(data);
    const pixelDataElement = dataset.elements.x7fe00010;
    const buffer = Buffer.from(dataset.byteArray.buffer, pixelDataElement.dataOffset, pixelDataElement.length);

    const term = '\r\n';
    const boundary = crypto.randomBytes(16).toString('hex');
    const contentId = crypto.randomBytes(16).toString('hex');
    const endline = `${term}--${boundary}--${term}`;

    const contentType = `multipart/related;start=${contentId};type='application/octet-stream';boundary='${boundary}'`;

    const buffArray: Buffer[] = [];
    buffArray.push(Buffer.from(`${term}--${boundary}${term}`));
    buffArray.push(Buffer.from(`Content-Location:localhost${term}`));
    buffArray.push(Buffer.from(`Content-ID:${contentId}${term}`));
    buffArray.push(Buffer.from(`Content-Type:application/octet-stream${term}`));
    buffArray.push(Buffer.from(term));
    buffArray.push(buffer);
    buffArray.push(Buffer.from(endline));
    logger.info(contentType);
    return Promise.resolve({
      contentType,
      buffer: Buffer.concat(buffArray),
    });
  } catch (error) {
    logger.error(`Error preparing buffer from file: ${pathname}`);
    throw error;
}
```

**Comment by ruben-cruz** [comment]
I also tried the @vespasianvs code from [here](https://github.com/knopkem/dicomweb-proxy/blob/master/src/dimse/wadoRs.ts), but the generated buffer (application/octet-stream) seems to be invalid.

**Comment by knopkem** [comment]
Hi, the code above (including the typo) is probably related to dicomweb-pacs not the proxy.
The above seems to look alright, btw. both wadors responses (pacs and proxy) are currently successfully used with OHIF viewer. It's basically just wrapping the pixelbuffer into a multipart response as described here: https://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.5.html
How do you extract the buffer on the client and try to render it?
