### ISSUE TITLE
Get incorrect data of tag 00200037 (image orientation (patient))

### ISSUE THREAD

**Issue by dinhnam2901** [knopkem/dicomweb-proxy#12]
Hi @knopkem !
When I using the dicomweb proxy to get the metadata of series at link like: "localhost:5000/viewer/viewer/rs/studies/1.3.6.1.4.1.9328.50.17.81542716229005078623624107555150614426/series/1.3.6.1.4.1.9328.50.17.139140258220479953981546122144830800551/metaData".
1. The log in console of dicomweb proxy display the value of tag (0020, 0037) as: [1.000000\0.000000\0.000000\0.000000\1.000000\0.000000].
![VerboseLogging](https://user-images.githubusercontent.com/20145650/94227700-59948580-ff25-11ea-8445-b1a8632f2037.PNG)

2. The result of this link is a json string, and value of tag 00200037 as: [1].
![ActureResult](https://user-images.githubusercontent.com/20145650/94227736-7466fa00-ff25-11ea-9446-1fe3f7870e11.PNG)

The result of 1st and 2nd above is different. I wonder why. It should be the same together. I think 1st is oke, and 2nd is an issue, 2nd should be an array include 6 element as [1, 0, 0, 0, 1, 0] or some thing same.

Can you check this problem ?
Thank you so much !

**Comment by knopkem** [comment]
Hi,
yes you are right, it is a bug and I know where it comes from. Thanks for reporting, will fix asap.

**Comment by dinhnam2901** [comment]
I understand. Wait for you fixed it. Thank you!
And, the same problem was appear with the tag 00200032. Please check it too.

**Comment by knopkem** [comment]
Should work now with the latest version, let me know.

**Comment by dinhnam2901** [comment]
I will try with lastest version now.
Thank for your hark work.

**Comment by dinhnam2901** [comment]
It is work correctly.
Thank for your support!
