### ISSUE TITLE
Can't parse JSON answer in browser

### ISSUE THREAD

**Issue by dekardkrr** [knopkem/dicomweb-proxy#120]
Hello.
Help  me please.
I try to work with with branch ohiv-v3. 
I had started application on Debian, connection with CONQUEST server is successfull. I've read in coserver console.
But in browser I didn't see the result of search.
On the page Console in debug mode I've seen error :
`Uncaught (in promise) TypeError: e.replace is not a function
    at Object.formatPN (formatPN.js:11:41)
    at qido.js:53:20
    at Array.forEach (<anonymous>)
    at Pr (qido.js:46:15)
    at index.js:106:18
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at xa (app.bundle.3f65ae5e095a9c2d60ce.js:1:444104)
    at i (app.bundle.3f65ae5e095a9c2d60ce.js:1:444308)`

But on the page Network in browser I see the correct answer from backend with result json from CONQUEST server.

**Comment by knopkem** [comment]
Hi, had this problem with v3 also already and it's related to the structure of the patient name. See https://github.com/OHIF/Viewers/blob/v3-stable/platform/core/src/utils/formatPN.js
If the value in Alphabetic is anything other than a string (e.g. an array) the function fails. V2 handled this differently. Will have a look.

**Comment by knopkem** [comment]
In fact, trying out v3-stable, it seems there are many more issues at the moment. So for this project I will wait until v3 becomes main and than fix issues otherwise I will be running around to catch my tail. Sorry. Cheers.
