### ISSUE TITLE
How to connect with other Dicom viewers

### ISSUE THREAD

**Issue by Shuun26** [knopkem/dicomweb-proxy#128]
Hi @knopkem, sorry I didn't meant to upload the issue empty.

I was trying to connect dicomweb-proxy with weasis 4.x.
Don't really sure what url could I use with URL parameter.

![image](https://github.com/knopkem/dicomweb-proxy/assets/68860132/498e0006-0e8b-44b1-8843-1f50245afdc8)

Sorry for the dumb question, I'm really newbie on dicomweb-protocol.

Also this is my config file on dicomweb-proxy

"peers": [
    {
      "aet": "XPACS",
      "ip": "127.0.0.1",
      "port": 11112
    }
  ],
  // transfer syntax (e.g. compression of dicom files) used for transmission via wado and proposed to pacs
  "transferSyntax": "1.2.840.10008.1.2.4.80",

  // Set the mimeType to match the selected transferSyntax
  "mimeType": "image/dicom+jpeg",

  // only used for JPEG process 1,2,4
  "lossyQuality": 60,

  // log directory
  "logDir": "./logs",

  // cache directory
  "storagePath": "./data",

  // keep cache alive for how long after storage or -1 to disable
  "cacheRetentionMinutes": 60,

  // webserver port
  "webserverPort": 18883,

  // target PACS supports C-Get (if flase use C-Move instead)
  "useCget": true,

  // define which level to use for C-Move/C-Get fetches: STUDY, SERIES, IMAGE
  "useFetchLevel": "SERIES",

  // number of associations to PACS run in parallel
  "maxAssociations": 4,

  // do not issue c-find if search contains less characters
  "qidoMinChars": 0,

  // auto append * for patient name query
  "qidoAppendWildcard": true,

  // enable verbose logging to std::out (contains DIMSE output)
  "verboseLogging": false,

  // only disable when using wadouri instead of wadors
  "fullMeta": true,

  // disabled when empty, otherwise use connection url e.g. ws://localhost:6001
  "websocketUrl": "",

  // this is the secret your dicomweb-websocket-bride needs to configure too, make sure to keep it secret, and of course change it ,-) hint: use https://hashgenerator.de/
  "websocketToken":
    "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"
}

Note: I didn't change anything on Ohif Viewer configuration

**Comment by knopkem** [comment]
Please provide more information. What kind of viewers: web based, native application, where hosted ? Maybe bring examples.
The example ohif viewer (public directory) had a app config file that specifies the mapping to qido and wado routes.

**Comment by knopkem** [comment]
The above looks almost good. Can you try with:
http://localhost:18883/rs
If I find some time, will also try setting up weasis.

**Comment by Shuun26** [comment]
That worked thanks a lot @knopkem I really appreciate it.

![image](https://github.com/knopkem/dicomweb-proxy/assets/68860132/b52c1dc5-a9a6-4c5c-a977-5008e9427fe7)

**Comment by knopkem** [comment]
Awesome!
Let me know if you encounter any issues. To be honest I never tested with anything except the OHIF viewer. Cheers

**Comment by Shuun26** [comment]
So I ran into this problem with the thumbnails.
![image](https://github.com/knopkem/dicomweb-proxy/assets/68860132/e901a33d-d88c-4ee1-9d08-3c228b0763da)
The images display correctly, I'm still figuring out what's going on.

Note: I used this example from Weasis and the thumbnails display correctly
weasis://$dicom:rs --url "https://demo.orthanc-server.com/dicom-web" -r "patientID=5Yp0E"

**Comment by knopkem** [comment]
Ok, I just tested myself.
The issue is that images are requested as jpeg and not as DICOM (this is what OHIF viewer does). So this is currently a bit cumbersome. What you need to do is:
* go here and download the prebuild binaries for your os: https://dicom.offis.de/en/dcmtk/dcmtk-tools/
* if you are on windows this is: https://dicom.offis.de/download/dcmtk/dcmtk367/bin/dcmtk-3.6.7-win64-dynamic.zip
* extract it somewhere and copy the content of the "bin" directory directly into the root directory of dicomweb-proxy (actually you only need all the dlls and the executable "dcmj2pnm.exe")
* now it should work (however not ideal as sometimes windowing is not correct)

Will see if I can implement this natively (so the above would not be needed), but this will take quite some time.

**Comment by Shuun26** [comment]
Yes, this worked! Thank you so much @knopkem!
