### ISSUE TITLE
Error when getting the value of series number (tag 00200011)

### ISSUE THREAD

**Issue by dinhnam2901** [knopkem/dicomweb-proxy#13]
Dear @knopkem !
I using the dicomweb proxy to get the metadata of series.
In the case "value of series number is empty", dicomweb proxy will return the value of series number as an empty array.
![image](https://user-images.githubusercontent.com/20145650/94540529-c2a33280-0270-11eb-8be1-c00cbc14a2a6.png)

But, I reading in the wiki of dicom tag  at http://dicomlookup.com/lookup.asp?sw=Tnumber&q=(0020,0011), the type of series number is a number.
So, I thing, in this case, the dicomweb proxy should be return the value of series number as an empty string instead.
![image](https://user-images.githubusercontent.com/20145650/94540680-ed8d8680-0270-11eb-96ea-028d5b9fed57.png)

Can you help me check it ?

Thank you so much!

**Comment by knopkem** [comment]
Hi,
I remember that I mentioned this in the last issue, that the currently implementation isn't quite correct regarding the dicomweb standard. However your proposal is also wrong. You have to look at the standard which states how it should be done:
http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.5.html

Unfortunately, the decisions they took are a bit weird (at least from my point of view), basically the way it is handled is use case dependend:

1.) Single Value attribute: (this is the case you mentioned), here the standard wants to not include the Value attribute, thus the above would look like: 
```
"00200011": {
  "vr": "IS",
}
```
2.) Multivalue attributes: here the missing value shall be replaced by a **null** object:
```
"00200011": {
  "vr": "IS",
  "Value": [ 1 , null, 5, 1, 4, 1]
}
```
3.) Sequence attributes: here an empty object {} (this is how it is currently implement) shall be used:
```
"Value": [ { … }, { }, { … } ]
```

I can update it to be compliant to the standard, but I won't implement anything propriatory (even if it might be easier to use).

**Comment by dinhnam2901** [comment]
Thank for your answer.
I understand it.
