### ISSUE TITLE
hello, Chrome, Firefox, MPR is failed

### ISSUE THREAD

**Issue by frsdxr** [knopkem/dicomweb-proxy#132]
Since chrome, firefox, edge and safari cannot use Cross Origin Isolation, how do I enable and use MPR?

Uncaught (in promise) Error: SharedArrayBuffer is NOT supported in your browser see https://developer.chrome.com/blog/enabling-shared-array-buffer/
    Qe createFloat32SharedArray.js:7
    s cornerstoneStreamingImageVolumeLoader.js:83
    h cornerstoneStreamingImageVolumeLoader.js:137
    au volumeLoader.js:66
    iu volumeLoader.js:100
    _getVolumeViewportData CornerstoneCacheService.ts:216
    createViewportData CornerstoneCacheService.ts:80
    F OHIFCornerstoneViewport.tsx:401
    F OHIFCornerstoneViewport.tsx:443
    Ul React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
5 [createFloat32SharedArray.js:7:14](webpack:///node_modules/@cornerstonejs/core/dist/esm/utilities/createFloat32SharedArray.js)

​

**Comment by knopkem** [comment]
Why do you think that those browsers don't support it: https://caniuse.com/sharedarraybuffer
Last time I checked it was working on my chrome browser or is this for mobile?
I guess this is new with version 3 of the OHIF viewer. Guess it would be better to ask there or you can go back to V2.

**Comment by frsdxr** [comment]
That's right, the error occurred in V3.
I'll ask there, thanks.
