### ISSUE TITLE
Multiframe instances

### ISSUE THREAD

**Issue by andyle2k** [knopkem/dicomweb-proxy#137]
Hi, just wondering whether this works with multiframe instances?

I'm actually trying something similar creating a proxy between DIMSE PACS and WADO OHIF but in DotNet and C# instead. I'm also using Dicom JSON as the OHIF data source.

I've actually got most of it working all except for multiframe instances. OHIF expects the Dicom Web server to split each frame as its own dicom file. This is using Dicom JSON so maybe it's different when using Dicom Web as a datasource. 

Thanks.

**Comment by knopkem** [comment]
Hi, yes handling multiframe images is also defined in DicomWeb: https://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_10.4.1.1.1
The difference is that the route should only return the pixelbuffer of the selected frame, not the metadata again.
It's currently not handled by this proxy, see https://github.com/knopkem/dicomweb-proxy/blob/master/src/routes/routes.ts#L331 (the frame parameter is ignored). I guess I should implement it one day...
Usually you have options on the PACS that you want to connect, to disable multiframe sending (basically extracting on the PACS before sending). So far nobody complained.

**Comment by andyle2k** [comment]
Hey thanks for the reply. Let me close this. 

Do you have any public ways for me to contact you directly? There's quite a few things I want to pick your brain about if you don't mind. Otherwise, thanks again for the insight and good luck.

**Comment by knopkem** [comment]
Hi Andy,
sorry was sick for a while, sure you can contact me over at https://www.linkedin.com/in/knopkem/
Cheers
