### ISSUE TITLE
support includefield=all

### ISSUE THREAD

**Issue by mario-huang** [knopkem/dicomweb-proxy#150]
According to https://www.dicomstandard.org/using/dicomweb/query-qido-rs, QIDO-RS should support includefield=all.
When I use `/rs/studies?includefield=all`, I get this error `ERROR invalid result received`.

**Comment by knopkem** [comment]
Hey, you are right. The reason why this was not added was that at that at the time of creation the dicomweb standard had no such parameter: https://dicom.nema.org/medical/dicom/2018d/output/html/part18.html#sect_6.7
Also, my main motiviation for this project was to get the OHIF viewer easily running (without orthanc or dcm4chee)
Anyway, can add this parameter if you need it or you can also create a PR.

**Comment by mario-huang** [comment]
Got it, thanks.
