### ISSUE TITLE
Install v1.0.13 instead of 1.0.14

### ISSUE THREAD

**Issue by Khanshk** [knopkem/dicomweb-proxy#16]
Hello,
I had setup success dicomweb- proxy but not able to find 2d mpr button in 4.8.6.
So plan to move to 1.0.13 but when using  npm install dicomweb- proxy command it install  1.0.14 , also try command using #v1.0.13 at end but not succeed.  Let me know how to resolve this situation..my need is to use dicomwebproxy with viewer having 2d mpr.

**Comment by knopkem** [comment]
the proxy uses c-find when querying the pacs which does not provide sufficient information for MPR to work (this is why the button is automatically hidden). you can try the branch 'deep meta' in which it first fetches and parses the dataset to get the necessary meta data. A better solution would be to use the dicomweb-pacs server (see my other repo). cheers

**Comment by Khanshk** [comment]
Got it ..thanks 
I install dicomweb-pacs successfully its working fine with orthanc.  How ever notice one thing that jpeglossless non hierarchy 14 transfer syntax not supported in viewer is it right?

**Comment by knopkem** [comment]
Yes, currently the server re-compresses when receiving the data, which I will fix soon in the underlying dicom toolkit
