### ISSUE TITLE
Error while proxy server working for a bit

### ISSUE THREAD

**Issue by ferranalma3d** [knopkem/dicomweb-proxy#24]
Hi,

I'm getting this error, any idea?

![image](https://user-images.githubusercontent.com/69808749/117428224-28058300-af26-11eb-90dd-cf6b3fb1cdc8.png)

**Comment by ferranalma3d** [comment]
thanks a lot as always

**Comment by knopkem** [comment]
I think you are running an older version and there have been fixes regarding node-persist and throwing unhandled exceptions. Try upgrading first.

**Comment by ferranalma3d** [comment]
ok! thx!
