### ISSUE TITLE
Problem network connection

### ISSUE THREAD

**Issue by frsdxr** [knopkem/dicomweb-proxy#29]
Hi,
when I try to access the proxy webview on another Connection Denied computer, through the network IP:
http://192.168.0.10:5000
Says connection refused.

I can only do it on the local connection, how do I run on a network?

**Comment by knopkem** [comment]
This is most likely not related to the proxy. Check if your firewall blocks port 5000 (in production one would set it up to port 80 via the config file).

**Comment by frsdxr** [comment]
I did the test on Ubuntu 16 and Windows and the same problem happened, trying to access the server that runs the dicomweb-proxy via the network.

It only works on localhost, via IP network even on localhost of the refused connection and without firewall.

**Comment by frsdxr** [comment]
I created a hello world project, using the same port 5000 and it opened the normal Hello World phrase in the browser.

when I use the dicomweb-proxy project and start, npm start it works, but only accessing http://localhost and http://127.0.0.1, if I try to access using the local network ip http:///192.168.0.3 he of the connection refused in the browser.

I also installed it on a dedicated cloud server and the same problem happened when trying to access http://IP.MY.SERVER:5000 from the refused connection.

**Comment by knopkem** [comment]
Hi, I just tried and indeed could see the problem, interesting. Must have been introduced lately due to an npm package update. Will fix and come back to you asap. Cheers.

**Comment by frsdxr** [comment]
Thank you very much friend, Cheers and peace to you.

**Comment by knopkem** [comment]
Indeed, fastify was not listening on all interfaces only localhost. I guess I only tested it with the old version (express) from a remote pc. Should work now in the latest version. Thanks for reporting.

**Comment by frsdxr** [comment]
I'm going to test it right now. thanks

**Comment by frsdxr** [comment]
Here it worked in a normal network, using the integrated visualization.

A doubt:
in the app-config.js file is it possible to configure for a current OHIF version with the dicomweb-proxy configuration?
Any configuration examples?

**Comment by knopkem** [comment]
You can generate a newer version of OHIF and put it in the public folder. Just make sure that the app-config.js is adding a dicomWeb server like it is in the source right now. However, at one point OHIF refactored their implementation of WADOURI (which they normally hardly use, because WADORS is so superior) and made it incompatible for any use with a proxy (not just this proxy, as it requires metadata that the proxy doesn't have). Anyway, I filed a bug report and PR fix which never got merged, so I guess the current latest version is not working. There is a OHIF V5 sprint branch (with heavy refactoring) that fixed the bug though. You can build it from my fork https://github.com/knopkem/Viewers which contains the fix. Good luck.

**Comment by frsdxr** [comment]
I got the package from your git https://github.com/knopkem/Viewers

and I gave yarn install command then yarn run dev

which example connection in default.js do I put?
I tested some here example below and I couldn't

  servers: {
    dicomWeb: [
      {
        name: 'PROXY',
        wadoUriRoot: 'http://192.168.0.10:5000/wadouri,
        qidoRoot: 'http://192.168.0.10:5000/viewer/rs',
        wadoRoot: 'http://192.168.0.10:5000/viewer/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },

and also

  servers: {
    dicomWeb: [
      {
        name: 'PROXY',
        wadoUriRoot: 'http://192.168.0.10:5000/wadouri,
        qidoRoot: 'http://192.168.0.10:5000/rs',
        wadoRoot: 'http://192.168.0.10:5000/rs',
        qidoSupportsIncludeField: true,
        imageRendering: 'wadouri',
        thumbnailRendering: 'wadouri',
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
      },
    ],
  },

but without success, it doesn't work.

**Comment by frsdxr** [comment]
It worked in your version of https://github.com/knopkem/Viewers.

However, the names of the patients are not carrying, only the names of the studies.

In the listing, the names are like (EMPTY)
