### ISSUE TITLE
Unable to view studies in OHIF

### ISSUE THREAD

**Issue by DANIELMWAMBI** [knopkem/dicomweb-proxy#3]
![image](https://user-images.githubusercontent.com/7789532/86532242-0a642900-bed1-11ea-8465-6eb52d5e8186.png)

am able to load the study list but i cannot open the study instances

**Comment by knopkem** [comment]
Hi, I suspect that you are trying against a recent version of the OHIF viewer. Note that there is currently a bug in OHIF with wadouri that makes it incompatible. I filed a bug report but it's not yet merged. In the meantime you can use my branch 'deepMeta' which uses wadors an should work. cheers.

**Comment by DANIELMWAMBI** [comment]
I used the ohif web viewer that comes pre installed in dicom-webproxy

**Comment by knopkem** [comment]
In this case it's likely that your PACS does not support C-GET which is used by default. You can change to C-MOVE by setting useCGet option to false in the default.js config file. For C-MOVE you need to configure your PACS to know the proxy.

**Comment by DANIELMWAMBI** [comment]
How do i configure the PACS to know the proxy for C-MOVE?

**Comment by knopkem** [comment]
You should read the manual of the pacs, what pacs are you using?

**Comment by DANIELMWAMBI** [comment]
Am using clearcanvas the latest build

**Comment by DANIELMWAMBI** [comment]
Am currently using clearcanvas

**Comment by knopkem** [comment]
sorry can't help you with this, the user manual should tell how to configure a client to perform a C-MOVE.

**Comment by DANIELMWAMBI** [comment]
i think the problem is in clearcanvas ,since am not able retrieve studies using their client from the server
