### ISSUE TITLE
Show rulers on the image

### ISSUE THREAD

**Issue by joweste** [knopkem/dicomweb-proxy#33]
Hi,

I just installed dicomweb-proxy and I can access conquest images.

I´d like to show horizontal and vertical rulers in the image.

How can I do that?

**Comment by knopkem** [comment]
Hi,
the dicomweb-proxy only implements the translation between the networking standards (dicomweb to dimse and back) for data exchange. It comes with an example dicomweb viewer which happens to be the OHIF viewer see https://github.com/OHIF/Viewers but is not limited to this viewer. For questions regarding the viewer please refer to their repo.
