### ISSUE TITLE
Can't connect to proxy

### ISSUE THREAD

**Issue by gmer16** [knopkem/dicomweb-proxy#4]
Hi, 
I'm trying to test your component sending data from a python script.
I setup the "target" in the proxy configuration file as a locally running orthanc instance.
When I start the proxy the "target" connection test (C-ECHO) succeeds.

However, I'm not able to send images from my test script, 
what is the correct configuration for the endpoints?

```
from dicomweb_client.api import DICOMwebClient
import pydicom

client = DICOMwebClient(
    url="http://localhost/",
    qido_url_prefix="rs",
    wado_url_prefix="wadouri",
    stow_url_prefix="rs"
)

filename = "./data/IM-0001-0001.dcm"
dataset = pydicom.dcmread(filename)
client.store_instances(datasets=[dataset])
```

Thanks

``

**Comment by knopkem** [comment]
Hi,
not sure to understand the issue correctly. From what you wrote I assume that you try to store dicomdata in orthanc using the proxy (basically pushing data to the proxy which pushes to orthanc). 
Unfortunately this is not yet implemented as the goal was to allow DICOMWEB image viewers to connect to a PACS and pull images mainly. However it is on my todo list, but I can't give you any due dates for it, sorry.

**Comment by gmer16** [comment]
Ok,
thank you for the clarification, cheers.

**Comment by knopkem** [comment]
Btw. you don't need a proxy with orthanc as it natively supports dicomweb: https://www.orthanc-server.com/static.php?page=dicomweb
