### ISSUE TITLE
Dicomweb proxy returns corrupted data when i login in the ohif standalone viewer web page

### ISSUE THREAD

**Issue by truitaman** [knopkem/dicomweb-proxy#5]
Hi,

I was trying to connect to a dcm4chee arc light PACS with your application but it returns an error in the dimse output message.

i added your node to the AET configuration of dcm4chee arch light.

mainly it displays that dicom fields are corrupted 

here is the output:

dicomweb-proxy Application seems to run fine.

![dicomweb-proxy error](https://user-images.githubusercontent.com/43993518/88318491-14808700-cd1b-11ea-8d18-826e9527e820.png)

pd: i noticed u use pdu max size to 16384 and dcm4chee 16378 so i changed it, still it displays same error.

tested with c-get and c-move.

Any idea how to fix this issue ?

Br,

**Comment by knopkem** [comment]
Hi,
for now I don't know what could be the reason for the incompatibility. I used the dcmtk framework which is used for the dimse before with arc light without any issues, but haven't tested the proxy. If I find the time I will try to reproduce it and get back to you. thanks for reporting. cheers

**Comment by knopkem** [comment]
looking at the logs again it seems to be an issue on the proxy side and not with the communication between the pacs. The message about Bad override key is before C-find is performed. Will check tomorrow.

**Comment by knopkem** [comment]
Unfortunately without a debugger running, this is hard to trace as the error message is too generic.
All I can say is that it's very likely not related to your PACS but rather an issue with your system (node ->dicom framework).
What os and what node version do you use?

**Comment by truitaman** [comment]
Good morning,

ubuntu server, node v14.6.0

**Comment by knopkem** [comment]
The issue might come from NAN (it was build with nodejs 12). If possible you could test with this version (e,g, using nvm).
Will try to reproduce the issue with ubuntu and node 14, let's see.

**Comment by truitaman** [comment]
Hi,

i created another vps and under node js 12, same error.

[
![ubuntu12](https://user-images.githubusercontent.com/43993518/88378975-56a0db80-cda2-11ea-8bce-4bd4c0c4916b.png)
](url)


same issue.

**Comment by alexandremg85** [comment]
Try exporting DCMPATH then npm start

In my case, i did it in linux and node 12:
 `export DCMDICTPATH=./node_modules/dicom-dimse-native/dcmdata/data/dicom.dic`

This issue is related to [dcmtk](https://forum.dcmtk.org/viewtopic.php?t=4887).
and J Riesmeier said that "You should enable support for the builtin data dictionary...see [datadict.txt](https://support.dcmtk.org/docs/file_datadict.html)"

**Comment by knopkem** [comment]
Thanks @alexandremg85, I've patched the dicom-dimse-native dependency using the buildin dictionary, so the above should not be necessary anymore.

**Comment by truitaman** [comment]
So i need to reinstall the dicomweb-proxy?

Thx for all your help.

**Comment by knopkem** [comment]
Can you try with the repo and not the npm plugin?
* git clone https://github.com/knopkem/dicomweb-proxy
* cd dicomweb-proxy
* npm run build
* edit config
* npm start

This should use the latest version (1.0.6) of the dicom-dimse-native plugin. You don't need to export the DCMDICTPATH anymore as the plugin comes with the dictionary included now. Don't use sudo to run the commands. Let me know if this helps.

**Comment by truitaman** [comment]
when i run npm run build returns error:

sudo npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-27T07_44_31_803Z-debug.log

Any idea?

**Comment by knopkem** [comment]
Ah sorry, there is no build step needed, just skip it.

**Comment by truitaman** [comment]
Same error.

![same_error](https://user-images.githubusercontent.com/43993518/88519869-197f5800-cff3-11ea-9dfd-0c19b487e28b.png)

**Comment by knopkem** [comment]
Ok, so maybe it's not the missing dictionary in your case. Will try to install arc light (docker) and reproduce. Sorry.

**Comment by truitaman** [comment]
Wait a bit sir,

i did launch again 

 npm i -s dicom-native-addon

and now yes it displays study list...

and when i click study - 

![viewer_not_loaded](https://user-images.githubusercontent.com/43993518/88521428-2e5ceb00-cff5-11ea-938e-6a3c9ba154ba.png)

and console logs  : 

![consoleoutput](https://user-images.githubusercontent.com/43993518/88521517-4f254080-cff5-11ea-8596-1586e7bbbba1.png)

i will dig in my side if it's something from the network or maybe the configuration in the PACS side just in case.

**Comment by knopkem** [comment]
Ok, this is better try to use C-GET as it should be supported and check the
browser console for errors.

**Comment by truitaman** [comment]
yep with c-get looks good. 

it's possible to use my own pure dicomweb viewer to interact directly with dicomweb-proxy so avoid using OHIF viewer?

**Comment by knopkem** [comment]
Great that it works now!
Yes it should be possible to use any dicomweb viewer, however it depends on
what the viewer expects. For example current master branch only supports
fetching images via WADO-URI but not WADO-RS as this requires to also
provide meta information (information that usually cannot be acquired via
C-FIND but rather by parsing the files) I made a prototype in the branch
"deepMeta" which can use Wado-RS too.
Just look at the app.js file to see the translation between dicomweb and
dimse, it's rather trivial. All you need to do is configure your dicomweb
viewer to connect to the webserver (port 5000 by default) and it should
work.

**Comment by pablosbravo** [comment]
Hello everyone! In theory, from what I saw regarding OHIF, the latest version integrates the dicomweb proxy to support PACS that don't work with WADO. Does anyone have an example of the 'app-config.js' configuration or a docker-compose file? I would greatly appreciate it.
