### ISSUE TITLE
Dowloaded studies from PACS

### ISSUE THREAD

**Issue by mk-rocket** [knopkem/dicomweb-proxy#61]
What is the data retention policy of the downloaded studies (via C-GET/C-MOVE). Do they get purge or do they need to be manually deleted?

**Comment by knopkem** [comment]
currently there is none, so you must cleanup from outside. I had this built on before converting to typescript and refactoring, did not port it, but could bring it back if you need it.

**Comment by knopkem** [comment]
Hi @mk-rocket, I brought back the automatic cleanup of fetched studies (defaults to 60 minutes retention time) but you can configure it via: ```cacheRetentionMinutes={NumberInMinutes}```

**Comment by mk-rocket** [comment]
Thanks!
