### ISSUE TITLE
Cannot access custom page

### ISSUE THREAD

**Issue by thanhtd1012** [knopkem/dicomweb-proxy#7]
Hi @knopkem !
I just create a custom page in ohif to login. In ohif, it is work with url such as localhost:3000/login.
I create a build product ohif and override it into dicomweb proxy. I access home page at localhost:5000, it is redirect into localhost:5000/viewer and display correctly with my expected. 
But, i access  localhost:5000/login, an error will appear as same as picture bellow:

![Capture](https://user-images.githubusercontent.com/70577879/92101922-08064880-ee08-11ea-9bc2-1aafb0b71a6c.PNG)

Can you help me to find out of reason, and what should I do with this situation ?
Thank you so much!

**Comment by knopkem** [comment]
Your can't use localhost:5000/login as this is the proxy server and has no such root. You should update ohif to automatically redirect to your login page when index.html is called. Look at app.js it only loads the static file in public/viewer/index.html which needs to be your main entry point. Btw. you can also use keycloak server with a custom page which is supported and the recommended way. Good luck.

**Comment by thanhtd1012** [comment]
I understood. Thank you for your support!

**Comment by thanhtd1012** [comment]
Close!
