### ISSUE TITLE
patient name, date, window and level

### ISSUE THREAD

**Issue by ziedallouch** [knopkem/dicomweb-proxy#71]
Hi,
First of all thanks for a great software, dicomweb proxy is connected successfully with conquest but some information like patient name, date, window and level are not retrieve 
![CaptureOHIF](https://user-images.githubusercontent.com/49563638/154436368-00e29093-fe08-420b-84e6-b72fc6be23e6.PNG)
![CaptureOHIF2](https://user-images.githubusercontent.com/49563638/154436375-55121635-77cd-4e7c-942c-8d74d9a60770.PNG)

**Comment by knopkem** [comment]
indeed, never noticed it before. will look into it.
