### ISSUE TITLE
Search multiple Modalities doesn't work

### ISSUE THREAD

**Issue by thanhtd1012** [knopkem/dicomweb-proxy#78]
Hi @knopkem!
When I use dicomweb proxy to filter study list data for Viewers-3-stable:
Github:
- Dicomweb-proxy: https://github.com/knopkem/dicomweb-proxy
- Webviewer: https://github.com/OHIF/Viewers/tree/v3-stable/

There is the following issue:
"Search multiple Modalities doesn't work".

Example:
(1). I search with a Modalities ="CT".
request:  http://localhost:3000/?modalities=CT
![image](https://user-images.githubusercontent.com/70577879/163147462-bee916e5-6348-4e0f-a36c-43d4ccc2786c.png)

(2). I search with a Modalities ="SM".
request:  http://localhost:3000/?modalities=SM
![image](https://user-images.githubusercontent.com/70577879/163147653-502a3310-fb54-48e7-8701-0bd1b704cadd.png)

(3). I search with multiple Modalities ="CT, SM".
request:  http://localhost:3000/?modalities=CT%2CSM
![image](https://user-images.githubusercontent.com/70577879/163147880-5763cf4f-46bf-4702-84aa-4ac711103949.png)

Both (1) and (2) , it works.
Only (3), It does not work.

What should I do to get it ?
Thank you so much !

**Comment by knopkem** [comment]
Hi, not sure why it doesn't work, will have a look.

**Comment by thanhtd1012** [comment]
Hi @knopkem!
I got it.
I am looking forward to receiving your reply as soon as.

**Comment by knopkem** [comment]
Sorry too many issues still with v3-stable. Will wait until it becomes main.
