### ISSUE TITLE
C-Find error

### ISSUE THREAD

**Issue by arunnad007** [knopkem/dicomweb-proxy#82]
![cap](https://user-images.githubusercontent.com/23183808/165432047-786dd5aa-a957-4cd7-b16d-89baab9ad17e.PNG)
![Cap1](https://user-images.githubusercontent.com/23183808/165432129-46515618-ca16-4861-ba28-222a816dac90.PNG)
![cap2](https://user-images.githubusercontent.com/23183808/165432136-0e07942a-b1f0-42d1-a385-36f7c97eb346.PNG)

Hello,
i am using orthanc as a pacs server and would like to communicate in normal dicom protocol with OHIF.
DICOM association is succesful.But i cant view the images stored in the pacs on OHIF viewer.
I have attached error log above.
Thanking you,
Arun

**Comment by knopkem** [comment]
Hi,
first of all: orthanc supports DICOMWEB  (communication interface for OHIF) natively (via a [plugin ](https://book.orthanc-server.com/plugins/dicomweb.html)that is included in the installer I think). The native implementation will always be faster than this proxy so you should definitely use it. 

Regarding the issue, please check if there is a 'data' folder available at the root of the proxy, the last error indicates that this is somehow not the case. Good luck.

**Comment by arunnad007** [comment]
Unfortunately for raspberry pi, it is not working. Anyway,thanks

**Comment by knopkem** [comment]
Ah, you mean the orthanc plugin doesn't work, or dicomweb-proxy?

**Comment by arunnad007** [comment]
Hi
I meant Ohif .
