### ISSUE TITLE
Cannot get the Modality property of series

### ISSUE THREAD

**Issue by dinhnam2901** [knopkem/dicomweb-proxy#9]
Hi @knopkem!
When I using dicom proxy to get metadata of series, I always receive the Modality property as "undefined".
Please refer at image bellow:
![image](https://user-images.githubusercontent.com/20145650/92350319-dab8e380-f102-11ea-9a5f-d56c230b0978.png)
I wonder why!
Can you tell me a solution to resolve it ?
And, can you tell me how to get patient information including: date of birth, gender, address ?

Thank you so much!

**Comment by knopkem** [comment]
Hi,
can you update to the latest version. (Make sure it uses dimse-native plugin 1.0.8) and enable 'verboseLogging: true' in the config file. Then you can investigate the logs and post it here.

**Comment by dinhnam2901** [comment]
I understood. I will trying it. 
Thank you very much!

**Comment by dinhnam2901** [comment]
I have been update to new version, but, it is still, not work. I trying to add dicomtag for it, as:
